name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Grants write permissions to allow pushing README updates

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Ensure correct directory
        run: |
          echo "Current directory:"
          pwd
          ls -l
          echo "Directory contents:"
          ls -l

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=PackTravel.settings" >> $GITHUB_ENV
          echo "Environment variable DJANGO_SETTINGS_MODULE set to PackTravel.settings"

      - name: Run Django checks
        run: |
          python manage.py check

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
          file: coverage.xml


