name: Codacy Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # use the version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage  # in case it's not in requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml  # generates a coverage.xml file

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s -- report -r coverage.xml
