name: Python CI with Codacy Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov codacy-coverage  # Install pytest, pytest-cov, and codacy-coverage

      - name: Set DJANGO_SETTINGS_MODULE
        run: |
          echo "DJANGO_SETTINGS_MODULE=PackTravel_G29.settings" >> $GITHUB_ENV  # Set environment variable to point to your settings

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests with maxfail=1 to stop after one failure

      - name: Generate coverage report
        run: |
          pytest --cov=your_project --cov-report=xml  # Replace 'your_project' with your project folder
          
      - name: Upload coverage to Codacy
        run: |
          codacy-coverage -r coverage.xml  # Upload coverage report to Codacy

      - name: Commit Codacy badge to README
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Replace <codacy_badge_placeholder> with the actual Codacy badge URL
          sed -i 's|<codacy_badge_placeholder>|https://app.codacy.com/project/badge/Coverage/<YOUR_PROJECT_ID>?branch=main|' README.md
          git add README.md
          git commit -m "Update README.md with Codacy badge"
          git push
