name: Codacy Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Ensure correct directory
        run: |
          echo "Current directory:"
          pwd
          ls -l
          # Change to the correct directory, which is `PackTravel` (not `PackTravel_G29`)
          cd PackTravel
          echo "Changed to PackTravel directory:"
          pwd
          ls -l

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=PackTravel.settings" >> $GITHUB_ENV
          echo "Environment variable DJANGO_SETTINGS_MODULE set to PackTravel.settings"

      - name: Run Django checks
        run: |
          cd PackTravel  # Change to the project directory if needed
          python manage.py check

      - name: Run tests with coverage
        run: |
          cd PackTravel  # Ensure we're in the correct directory for Django
          coverage run --source='.' manage.py test
          coverage xml

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s -- report -r coverage.xml

      - name: Set Badge URL
        id: codacy_badge
        run: |
          badge_url="https://app.codacy.com/project/badge/Coverage/${{ github.repository }}?token=${{ secrets.CODACY_PROJECT_TOKEN }}"
          echo "Badge URL: $badge_url"
          echo "::set-output name=badge_url::$badge_url"

      - name: Update README with Codacy badge
        run: |
          echo "Updating README.md with Codacy badge"
          badge_url=${{ steps.codacy_badge.outputs.badge_url }}
          sed -i "s|<codacy_badge_placeholder>|![Codacy Badge]($badge_url)|g" README.md
          git add README.md
          git commit -m "Update README with Codacy coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
