name: Codacy Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust as needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Set environment variables
        env:
          DJANGO_SETTINGS_MODULE: "PackTravel_G29.settings"  # Correct path to settings file
        run: echo "Environment variables set"

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml  # Generates a coverage.xml file

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s -- report -r coverage.xml
