name: sphinx-autogenerator

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build documentation and commit
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  sudo apt-get install python3-sphinx                
                  sphinx-apidoc -f -o docs/source PackTravel
                  sphinx-apidoc -f -o docs/source publish
                  sphinx-apidoc -f -o docs/source request
                  sphinx-apidoc -f -o docs/source search
                  sphinx-apidoc -f -o docs/source user

        # ===============================
