name: Testcases check

on: [push]

# defaults:
#   run:
#     working-directory: user

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:

    - name: Test the features
      run: |
        pwd
        ls
        python manage.py test user
        

